### ISSUE TITLE
window.nSQLite undefined

### ISSUE THREAD

**Issue by hamzahio** [ClickSimply/cordova-Nano-SQLite#1]
it try to use this plugin with cordova but i got this error 
```
window.nSQLite // undefined

```

**Comment by ClickSimply** [comment]
Hey Hamzahio,

How are you including the script in your App?  If you could show me your initialization code that would help me figure out what's happening.

Best,
Scott

**Comment by ClickSimply** [comment]
I just pushed version 1.3.0, please remove the current plugin completely and install the newest version.  That should resolve everything. :)

**Comment by ClickSimply** [comment]
There hasn't been any activity on this for almost 2 weeks, marking resolved.
