### ISSUE TITLE
1.2.0 is not compatible with latest nano-sql

### ISSUE THREAD

**Issue by dhananjaykumar880** [ClickSimply/cordova-Nano-SQLite#2]
The new release is not compatible with latest nano-sql. it returns a lot of typescript error because nano-sql moved their code to more specific typescript code.

Could you have a look and release a new version with compatibility.

**Comment by ClickSimply** [comment]
Hello,

Just pushed 1.3.0, should be working without an issue now. :)

Best,
Scott

**Comment by RenatoSilveiraGomes** [comment]
Hello! I'm currently using nanoSQL 1.4.3 and cordova-Nano-SQLite 1.3.0 but when trying to run got these errors:

![image](https://user-images.githubusercontent.com/24719606/38770990-6cf0c9a4-3ff1-11e8-86ec-43319059620d.png)

What awesome tool! Can you help me, please?

Thank you very much!

**Comment by ClickSimply** [comment]
Looks like you don't have the `@types/websql` package installed.  Just pushed an update where that dependency has been moved from `devDependencies` to `dependencies`.  `npm i @types/websql` or installing the newest version should resolve this.

**Comment by RenatoSilveiraGomes** [comment]
All systems go!!! nanoSQL 1.4.4 and cordova-Nano-SQLite 1.3.1 working like a charm! Thank you very much man, and congratulations for your amazing job!

**Comment by ClickSimply** [comment]
Marking this as resolved..
